# Generated by Django 3.1.4 on 2020-12-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_password', models.CharField(max_length=25)),
                ('customer_phone_number', models.IntegerField()),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('employee_password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MobileModels',
            fields=[
                ('mobile_model_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('mobile_name', models.CharField(max_length=100)),
                ('mobile_screen', models.CharField(max_length=500)),
                ('mobile_camera', models.CharField(max_length=500)),
                ('mobile_battery', models.CharField(max_length=500)),
                ('mobile_ram', models.CharField(max_length=500)),
                ('mobile_rom', models.CharField(max_length=500)),
                ('mobile_os', models.CharField(max_length=500)),
                ('mobile_warranty', models.CharField(max_length=500)),
                ('mobile_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10)),
                ('mobile_model_id', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MobileImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_image', models.ImageField(upload_to='images')),
                ('mobile_model_id', models.ForeignKey(db_column='mobile_model_id', on_delete=django.db.models.deletion.CASCADE, to='database.mobilemodels')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='database.customer')),
                ('mobile_model_id', models.ForeignKey(db_column='mobile_model_id', on_delete=django.db.models.deletion.CASCADE, to='database.mobilemodels')),
            ],
        ),
    ]
